spring.application.name=api-gateway
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
server.port=9191
management.endpoints.web.exposure.include=*

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=DEBUG

# Routes for Employee Service
spring.cloud.gateway.routes[0].id=EMPLOYEE-SERVICE
spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**

# Routes for Department Service
spring.cloud.gateway.routes[1].id=DEPARTMENT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/departments/**

#Routes for Organization Service
spring.cloud.gateway.routes[2].id=organization-service
spring.cloud.gateway.routes[2].uri=lb://organization-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/organizations/**

management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.org.springframework.web=DEBUG

#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*

#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE

## === OAuth2 Client Registration ===
#spring.security.oauth2.client.registration.azure.client-id=45977196-a728-4f1b-a054-772b2dbe19f0
#spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.azure.redirect-uri=http://localhost:9191/login/oauth2/code/azure
#spring.security.oauth2.client.registration.azure.scope=openid, profile, email, User.Read
#spring.security.oauth2.client.provider.azure.user-info-uri= https://graph.microsoft.com/oidc/userinfo
#
## === OAuth2 Provider Configuration ===
#spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/1c4c0d85-a423-4bc4-afe9-8ed0a9420439/v2.0


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE

#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/1c4c0d85-a423-4bc4-afe9-8ed0a9420439/v2.0
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/1c4c0d85-a423-4bc4-afe9-8ed0a9420439/

#spring.security.oauth2.resourceserver.jwt.jwk-set-uri= https://login.microsoftonline.com/common/discovery/keys
logging.level.org.springframework.security=DEBUG


# --- SPRING SECURITY OAUTH2 CLIENT CONFIG FOR TOKEN RELAY ---

spring.security.oauth2.client.registration.azure.client-id=edbd2f5f-74b4-4614-b8f9-1aca5cb9fe35
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.azure.redirect-uri=http://localhost:9191/login/oauth2/code/azure
spring.security.oauth2.client.registration.azure.scope=openid,profile,email

spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/1c4c0d85-a423-4bc4-afe9-8ed0a9420439/v2.0
